### ISSUE TITLE
Base 64 formatting

### ISSUE THREAD

**Issue by MrBrezina** [bramstein/homebrew-webfonttools#2]
Does it make any sense to include tool to convert webfonts to CSS with Base64 strings?

**Comment by bramstein** [comment]
I think it would (though I generally frown on inlining fonts, except for very specific use-cases). Is there such a tool?

**Comment by davelab6** [comment]
The homebrew `coreutils` package contains the `base64 /path/to/font.woff` tool; you can do it also within, `require "base64"`

The CSS is something like,

``` css
@font-face {
font-family: 'someFontFamily';
src: url(data:application/x-font-woff;charset=utf-8;base64,BASE64DATASTRING) format('woff'),
     url('webfont.ttf') format('truetype');
font-weight: normal;
font-style: normal;
}
```
